name = "AutoHashEquals"
uuid = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
authors = ["Neal Gafter <neal@gafter.com>", "andrew cooke <andrew@acooke.org>"]
version = "2.0.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.7"
