name = "AutoHashEquals"
uuid = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
authors = ["andrew cooke <andrew@acooke.org>"]
version = "0.3.0"

[compat]
julia = "1"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Serialization", "Test"]
