name = "AutoHashEquals"
uuid = "97026771-8bcd-44fb-b7eb-f644370d63d3"
authors = ["Neal Gafter <neal@gafter.com>", "andrew cooke <andrew@acooke.org>"]
version = "1.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.6"
